#!/bin/bash
aws s3 cp index.html s3://regex.danwin.com/slides/ --acl public-read
aws s3 sync css s3://regex.danwin.com/slides/css/ --acl public-read
aws s3 sync js s3://regex.danwin.com/slides/js/ --acl public-read
